name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Awesome_Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npx awesome-lint

  Awesome_Bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Checks
        run: |
          ruby .github/osia_convert.rb
          gem install awesome_bot
          ruby .github/osia_get_links.rb
          awesome_bot README.md --allow-ssl --allow-redirect  -a 429
